### PR TITLE
Requester demo for SMS Authentication support

### PR DESCRIPTION
**Pull request by dshafer**
Updates the python demo to show how to use Toopher API to authenticate with SMS authentication (allows Toopher to work with non-smartphones). SMS Authentication demo is accessed by running the demo.py script with the --sms command-line argument.

### CODE REVIEW

**Comment by smholloway** [comment]
I'm a little concerned about how much additional code this adds to the demo. Do y'all think it's worth splitting the SMS demo into its own separate entity? Another idea is to make this into a gist and [blog](https://devblog.toopher.com/) about it.

**Comment by egrim** [comment]
I'm also concerned about cluttering up the demo.  I think we should
probably have two demos: one simple and another with all the bells and
whistles.

**Comment by smholloway** [comment]
Good idea @egrim. Is the current demo simple enough or do we need to extract some functionality? We can just rename Drew's file.

Any thoughts on naming? Perhaps `demo.py` and `advanced_demo.py`. I don't want to name it `complete` because keeping the bells and whistles demo up-to-date and complete is a big commitment. Along those lines, how do we show _all_ the features while maintaining a decent flow?

**Comment by egrim** [comment]
Let's keep "demo" up front (for sorting reasons).  demo_advanced.py would
work, but I'm open to other suggetsions.  demo_bells_and_whistles has more
character, but is probably too long (you could say it has too much/many
characters).

**Comment by trdarr** [comment]
@egrim 

> (you could say it has too much/many characters)

:+1:

**Pull request merged**
