### PR TITLE
Add Coveralls support

### PR DESCRIPTION
**Pull request by trdarr**
:microphone: Check, 1, 2, 3…

### CODE REVIEW

**Comment by smholloway** [comment]
So this will allow us to see our test coverage at https://coveralls.io/r/toopher? I like it.

**Comment by smholloway** [comment]
Still interested in this idea?

**Comment by egrim** [comment]
Are you asking someone specific?  If it's me: I haven't followed this so
I'm afraid I don't know if I'm interested or not.

**Comment by trdarr** [comment]
@egrim 

> Are you asking someone specific?

I assume he was asking me.

## 

@smholloway 

> Still interested in this idea?

Yes, but it's not at the top of my to-do list.

**Comment by smholloway** [comment]
It appears to me that the work is done and we're ready to merge. So, can we merge this? If not, what is our criteria for done?

**Comment by trdarr** [comment]
Yeah, what we have works. Do we care about code coverage for the tests?

**Comment by smholloway** [comment]
Test coverage seems useful to me. With Coveralls we can more easily tell if someone added code without adding sufficient tests. It's free and relatively easy to integrate :100:

**Comment by trdarr** [comment]
My comment was ambiguous. We care about code coverage for `__init__.py`, of course, but do we also care about code coverage for `tests.py`? That's what Coveralls currently gives us and it's why I was on the fence about this PR being “complete.”

**Comment by smholloway** [comment]
What am I missing? Looking at [the most recent build](https://coveralls.io/builds/653905) I see coverage numbers for `toopher/__init__.py`.

COVERAGE        FILE    LINES   RELEVANT    COVERED MISSED  HITS/LINE
96.26%      toopher/**init**.py 274 187 180 7   1.0
97.57%      tests.py    445 288 281 7   1.0

Red/green coverage output here: https://coveralls.io/files/168521327

**Comment by trdarr** [comment]
I didn't want to merge the PR until I was sure that we're okay with coverage for `test.py`, which that report includes in addition to coverage for `__init__.py`.

**Comment by egrim** [comment]
I don't think the coverage report for tests.py adds much information
(unless you're a test writer, I suppose).

**Comment by smholloway** [comment]
So, we need to figure out how to exclude coverage on `tests.py`? I don't think the information is dangerous--just not generally useful--so I vote to include it and :shipit:

**Comment by smholloway** [comment]
The test file is now omitted; see https://coveralls.io/builds/781900. I will merge tomorrow afternoon unless someone objects.

**Pull request merged**
